name: Build and Deploy
on:
  push:
    paths:
      - "resume.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Move index.html to root
        run: mv build/index.html index.html

      - name: Create pdf folder
        run: mkdir pdf

      - name: Move resume.pdf to pdf folder
        run: mv build/resume.pdf pdf/resume.pdf

      - name: Copy resume.json to root
        run: cp -f resume.json resume.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
