name: Build and Deploy

on:
  push:
    paths:
      - "resume.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Assuming build script creates resume.pdf

      - name: Print working directory (optional for debugging)
        run: pwd # Print current directory

      - name: Move resume.pdf to root (if needed)
        run: mv build/resume.pdf . # Assuming resume.pdf is in build/

      - name: Create pdf folder (if needed)
        run: mkdir -p pdf # Create pdf folder if it doesn't exist (-p flag)

      - name: Move resume.pdf to pdf folder (optional for organization)
        run: mv resume.pdf pdf/ # Move resume.pdf if desired

      - name: Copy resume.json to root
        run: cp resume.json .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
